kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: vote
  labels:
    app: voting-app
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "git@gitlab.com:m.grillet/openshift-voting-app.git"
      ref: master
    contextDir: voting-app/vote
  output:
    to:
      kind: ImageStreamTag
      name: vote:latest